### ISSUE TITLE
Consider removing Parse/TryParse

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#11]
Feedback from @tarekgh:

> In general from my experience with DateTime, Parse/TryParse is really problem and always causing problems especially when changing the culture default date/time patterns. I suggest we don't support Parse/TryParse and force only ParseExact/TryParseExact

Let's discuss pros/cons.

**Comment by mj1856** [comment]
I'll argue for parity.  Since they exist on `DateTime` and `TimeSpan`, they should exist here.

Who would like to take the counter-argument?  :)

**Comment by tarekgh** [comment]
I don't think parity is the priority compared to do right thing. you already deviated from parity for example when introduced SubtractMonths/Days. 
Parse/TryParse is source of many complains and people always expect something and no necessary happen. please consider not supporting it.

**Comment by mj1856** [comment]
Considering the position taken in other issues like #13, I'd rather leave the parsing methods intact at this time.  Thanks.
