### ISSUE TITLE
Limit range of add/subtract operations

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#13]
Feedback from @tarekgh:

> if we have Add/Subtract methods, then I think we need to limit the parameters to positive values. otherwise we should have Add only. I am trying to limit the confusion when using it

Discuss pros/cons

**Comment by rafidka** [comment]
DateTime currently only have Add*() methods, no Subtract*() methods (apart from Subtract()), so I would go for add only to align with DateTime and reduce confusion.

**Comment by mj1856** [comment]
I don't think I like the idea of limiting these methods to positive values.  Otherwise I can see consumers writing ugly code like this to work around it.

```csharp
Date result = days >=0 ? date.AddDays(days) : date.SubtractDays(-days);
```

I think it makes a little bit of sense that `DateTime` has a `Subtract(TimeSpan)` methods, because the alternative would be `dateTime.Add(timespan.Negate())` - which isn't as readable.  But for integers, I don't think it's too difficult to understand or use `date.AddDays(-1)`

Unless there are any objections, let's just drop the `SubtractDays`, `SubtractMonths` and `SubtractYears` methods.  It will probably reduce confusion.
