### ISSUE TITLE
Consider using ISO8601 as the default format

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#14]
Discuss #3

Pros: Alignment to ISO-8601, and downstream types like HTML 5 date input
Cons: Not aligned to existing `DateTime` behavior

**Comment by mj1856** [comment]
I agree on the surface, but digging deeper, I'm not 100% sure.  Especially when you consider #7.

**Comment by paulirwin** [comment]
IMO, if you want to deviate from an international standard, you should handle that yourself with a format string and/or culture info. That opinion out of the way, I'll grumble as I type it but I'll accept a ToIso8601String() or something similar.

**Comment by mj1856** [comment]
The core of the issue is alignment.  Let's do our best to keep things in the style of the existing types so they feel more natural to the current users.

Closing this in favor of having a `ToISOString` method, which will be tracked in #16.

Thanks! :)
