### ISSUE TITLE
Now, Today, etc.  Properties or Methods?

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#15]
Discuss #1

Pros: `DateTime.Now` and `DateTime.UtcNow` already exist as properties.  People are used to them.
Cons: Lots of comments [like this one](http://stackoverflow.com/a/5438039/634824)  that consider this to be a mistake, due to the non-deterministic characteristic of time.

I know how I *feel* about this, the question is - should we conform for sake of alignment, or take the approach of correctness?

**Comment by mj1856** [comment]
Side note - Noda Time is changing `IClock.Now` to `IClock.GetCurrentInstant()` for its upcoming version 2.0 release.

**Comment by rafidka** [comment]
I would recommend going for alignment, as otherwise developers will be confused when they use both DateTime and Date in the same project.

**Comment by mj1856** [comment]
@rafidka - you're probably right.  Whatever `DateTime` and `DateTimeOffset` do, we should do the same or the users will be surprised.

@tarekgh - Do you think there is any possibility to introduce a breaking change to make `Now` and `UtcNow` methods instead of properties on `DateTime` and `DateTimeOffset`?  Or is that too much to consider at this stage?

**Comment by rafidka** [comment]
@mj1856 re your question to @tarekgh, just wondering, shouldn't the .NET Core be compatible with .NET Framework as much as possible, so that people can start using .NET Core instead with minimal changes? If the answer is yes, isn't changing Now to Now() going to break thousands of people's code?

**Comment by tarekgh** [comment]
@mj1856 taking a breaking change in DateTime is not possible now as we need to respect the app compat. but if you are introducing a new type, you may think have the right design as no worry about the app compat

**Comment by paulirwin** [comment]
One way to look at DateTime.Now and related properties is (a) they're static, and (b) they return a new instance. So they don't have to be viewed the same way as instance properties. In that view, I think it makes sense that a static Date.LocalToday property would not be deterministic, whereas instance properties, particularly of a struct, IMO should always be deterministic.

**Comment by rafidka** [comment]
How is being static affects determinacy?

To be honest, the more I think about it, the more I am convinced that UtcNow and the like shouldn't be a property; being a property even breaks one of the rules of the Equals method when you write DateTime.UtcNow.Equals(DateTime.UtcNow):

"x.Equals(x) returns true, except in cases that involve floating-point types." -- https://msdn.microsoft.com/en-us/library/bsc2ak47%28v=vs.110%29.aspx

Practically, it might not break it, but theoretically it should break it, since the first DateTime.UtcNow gets executed before the second one, and thus they should return a different value.

**Comment by tarekgh** [comment]
just to reiterate, DateTime properties are not going to change because of app compat reason. 
for Date type, I don't think we should have Now/UtcNow but we'll have Today (Local/UTC). 
if we are going to have Time type (of TimeOfDay). we can have a parity with Date so we can have Time Now(Local/Utc)
if you feel DateTime did some mistake regarding Now, NowUtc, then fix it in the new types.

**Comment by paulirwin** [comment]
As somewhat of a counter-example to what I said about instance properties, how about System.Diagnostics.Stopwatch.Elapsed? I'm not against Today or Now (on TimeOfDay) being methods, but determinacy/idempotency is not a hard and fast rule. "Getting" the value of DateTime.Now feels natural as a property since it is static and returns a new instance, and in this case, I'd vote for consistency with DateTime.

**Comment by mj1856** [comment]
I the grand scheme of things, I think introducing these new types should feel natural for those used to the other types.  So, I'll rule on this one - we'll go for consistency.   `Date.Today`, `Date.UtcToday`, `TimeOfDay.Now`, `TimeOfDay.UtcNow`.

Should we still have methods for zone-specific values?
- `Date.TodayInZone(TimeZoneInfo)`
- `Time.NowInZone(TimeZoneInfo)`

How about adding those to existing types also?
- `DateTime.NowInZone(TimeZoneInfo)`
- `DateTimeOffset.NowInZone(TimeZoneInfo)`

BTW - I'm throwing those into `DateTimeEx` and `DateTimeOffsetEx` for now, even though they can't be extension methods since they're static.  The idea would be to put them in `DateTime` and `DateTimeOffset` during the merge.

**Comment by mj1856** [comment]
@tarekgh - Regarding AppCompat, I assume we'll also not be able to have `DateTime.Today` return a `Date` instead of a `DateTime`?

```csharp
//
DateTime d = DateTime.Today;  // current api
Date d = DateTime.Today; // proposed api
```
Would it make difference if we included another implicit cast operator to compensate for the old usage?

**Comment by paulirwin** [comment]
I'm in favor of adding DateTime.NowInZone (although I prefer the more explicit NowInTimeZone) and its DateTimeOffset companion. Perhaps we could implement them as DateTimeEx methods here for now as a prototype?

**Comment by tarekgh** [comment]
@mj1856  I think we don't need to touch DateTime and implement your library as OOB.

For raised issues like   
    DateTime.NowInZone(TimeZoneInfo) 
I believe you can have extension method on the TimeZoneInfo class itself and at that time it'll make more sense something like TimeZoneInfo.GetCurrentTime (or whatever name make more sense). 

as discussed in the original thread and what Krzysztof Cwalina recommended the following steps and I think we are doing the first step here:
1. People who feel passionate about fixing DateTime should design an initially OOB library that is "the right" library for dates and times. 
 2. In parallel, we should all work on extensibility features in XML, data APIs, etc. to help an arbitrary OOB library to integrate more nicely with these APIs. As I can guarantee you that even if the do design "the right" date and time APIs, some people will want to use noda time and others.
 3. Once "the right" library for dates and times is proven in the filed, we will consider adding it (or parts of it) to CoreFx.

**Comment by mj1856** [comment]
@tarekgh - sounds like you're talking about IoC, but I'm not sure how that would manifest in these scenarios, I'll give it some more thought, but I'm open to suggestions.

**Comment by tarekgh** [comment]
what you mean by IoC? :-)

**Comment by mj1856** [comment]
[Inversion of Control](http://en.wikipedia.org/wiki/Inversion_of_control)

This is usually done with interfaces, but the problem is that in many cases you would have to return a concrete type.  So even if there was some `IDateTime` or similar interface(s), it would be working with `DateTime` types...

We should probably be looking deeper into the extensibility points (xml, data apis, etc.) for missing interfaces that could be implemented in either this lib or others - but that won't address the main issues.

As an analogy, consider simple integers.  I could create an `IAddition<T>` interface, but it would be quite difficult to write a meaningful `IAmAnInteger` interface.

**Comment by tarekgh** [comment]
@mj1856 thanks Matt for clarification and thanks for your effort you put in the implementation. 
I would suggest in your assembly you add extension methods and implicit cast operator to handle the listed types conversion (sql date, Xml date...etc.) this will be enough at least to make the original requested scenario to work. this doesn't mean we'll not look at System.Data, System.Xml at some point. I just want to have the ball roll and we'll have some initial progress

@paulirwin as we already have  plan and Matt thankfully executing on it, can we close the issue #700 or you still have anything to discuss there? I am willing to help with any issue.

**Comment by paulirwin** [comment]
I am not in favor of closing the issue until one of two situations happens: the System.Date type is created in the repo, or the .NET team decides that it will not implement the change. Otherwise we'll lose track of it.

**Comment by tarekgh** [comment]
@paulirwin as we mentioned before, the initial implementation will be OOB as Matt is doing now. we will not add this to corefx repo. once the new OOB proven in the field as this is the right thing, at that time we'll consider adding it to the framework core. please review Krzysztof Cwalina comments which state this clearly. what is unclear in that which need to keep the issue open?

**Comment by paulirwin** [comment]
I'll continue this discussion back over on corefx #700
