### ISSUE TITLE
Consider convenience methods for formatting

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#16]
`DateTime` has convenience methods:
- `ToShortDateString`
- `ToLongDateString`
- `ToShortTimeString`
- `ToLongTimeString`

Should `Date` and `TimeOfDay` have these also?

How about also `ToISOString` to address #14 ?

**Comment by rafidka** [comment]
Again, I think it should have these methods for alignment with DateTime. I am happy to have this assigned to myself if you want someone to work on it.

**Comment by mj1856** [comment]
Go for it! :)

**Comment by rafidka** [comment]
@mj1856, I sent a PR for an implementation of this. One thing I would like to mention is that because the PCL version of .NET's DateTime doesn't have these convenience methods, I ended up implementing these methods by calling the ToString() method and passing in the relevant field from CultureInfo.DateTimeFormat object. Is that OK?

Another thing is that in implementing unit tests, I cannot make assumptions on the culture of the machine the tests are being run under, so for now I am only making assertions if the culture is en-US or en-GB, as otherwise I will have to spend hours and hours checking against all available culture infos :-)

Looking forward for your review.

**Comment by mj1856** [comment]
You can set the current culture so it's not ambiguous.  In fact, you might want a few tests that vary the culture so you can validate the output format changes.

````csharp
using System.Threading;
using System.Globalization;
...
Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-GB");
```

The existing implementation looks fine.  Please update the tests and I'll merge the PR.

Also, please include a `Date.ToIsoString()` method, which should be the `yyyy-MM-dd` format in the `InvariantCulture`.

**Comment by rafidka** [comment]
Actually, I already thought of changing the culture but I couldn't, because the PCL version of the .NET you added to the project doesn't have System.Thread, i.e. the code you put above doesn't compile.

**Comment by rafidka** [comment]
To be honest, I am not sure why I can't find System.Thread, because MSDN does say that it should be available even in portable .NET:

https://msdn.microsoft.com/en-us/library/system.threading.thread.currentculture%28v=vs.110%29.aspx

Notice the section "Version Information".

Any idea?

**Comment by mj1856** [comment]
Hmmm.. Same thing here.  I will investigate further.

If we have to, we can make the test projects non-portable.

**Comment by rafidka** [comment]
OK, in the mean time, I will push the implementation of ToIsoString() so that I can work on other stuff while you investigate this. Once we reach a conclusion, I can go back to the tests and improve them to include testing some few different cultures.

**Comment by mj1856** [comment]
For now, I just switched to a non-portable test project.  I had to also change the profile for the main project for some reason. Not sure exactly why.

This will be temporary, but will get us through for now so we can write all the necessary unit tests.  At some point, we'll need to build out a project that will fit within the corefx project structure.

**Comment by rafidka** [comment]
If this is temporary, won't we have problems building the unit tests later when/if we try to move the project to corefix?

**Comment by rafidka** [comment]
I will start creating branches now for the issues I am assigned to.

**Comment by rafidka** [comment]
I think we can close this issue once the PR I sent is merged.

**Comment by rafidka** [comment]
Thanks @mj1856 for merging PR #21. Closing this issue.
