### ISSUE TITLE
Optimize Date and TimeOfDay classes

### ISSUE THREAD

**Issue by rafidka** [mj1856/corefx-dateandtime#17]
Date and TimeOfDay frequently defines new DateTime and TimeSpan objects, respectively, in methods and properties like Date.AddYears(), Date.ToDateTimeAtMidnight(), TimeOfDay.Minutes, etc. This can be expensive if the user repeatedly make calls to these methods/properties. I suggest creating the required DateTime/TimeSpan objects in the constructor and storing it in a field. I understand that this means more storage per each Date and TimeOfDay object, but I cannot think of a better solution.

**Comment by mj1856** [comment]
Yes, optimization is necessary.  However additional fields are out of the question.

The functions just need to be decomposed into primitives.  I'll leave this issues open to track that effort.

**Comment by mj1856** [comment]
Completed.  Thanks!
