### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by rafidka** [mj1856/corefx-dateandtime#19]
We need to add more unit tests for Date and TimeOfDay structures. For the Date structure, I see we are missing tests for the following members:

* Today
* TodayLocal
* TodayUtc
* AddYears
* AddMonths
* AddDays
* ToString (all of its variants)
* Parse (all of its variants)
* TryParse (all of its variants)
* TryParseExact (all of its variants)
* Equals
* CompareTo
* IsLeapYear

I didn't go through the tests for the TimeOfDay structure, but I thought I would file this issue and update it later when I have more information about TimeOfDay structure.

**Comment by mj1856** [comment]
Yep.  I pushed what I had so we could get started.  Thanks for adding an issue.

**Comment by rafidka** [comment]
Great. I am happy to work on this as well if you want. By the way, sorry if the question seems silly but I just recently started contributing to .NET: how do assign a task to more than one person? Like for this issue if say both you and myself work on it?

**Comment by mj1856** [comment]
Just go ahead and do whatever you think is important.  You don't need to wait for approval.  This is all very informal.

It will all work out in PR.  :)

**Comment by mj1856** [comment]
I've added a bunch of tests.  More to come. :)

**Comment by mj1856** [comment]
Will add more after move to corefxlab
