### ISSUE TITLE
Non-PCL version of assembly?

### ISSUE THREAD

**Issue by paulirwin** [mj1856/corefx-dateandtime#2]
I attempted to add [Serializable] and ISerializable to the types and then I realized it was a PCL. Are you open to creating a second project that is a .NET 4.5 class library, referencing the same files and using #if directives for PCL vs non-PCL?

**Comment by mj1856** [comment]
Yeah, I saw the same thing, so I left it off for now.  Ultimately, it needs to compile under the same build as the rest of corefx/coreclr.  We should see how they have their project configuration and align to that.

**Comment by paulirwin** [comment]
The CoreCLR project doesn't handle PCL at all it looks like: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/DateTime.cs

**Comment by mj1856** [comment]
I must say, I'm a bit confused about this.  All the projects in corefx are PCL, but with some non-standard project configuration.  I think we'll need to align to that.  I'm still not 100% up to speed on how corefx and coreclr hook together.

I'd be glad for a PR to pull this into alignment.  I don't want to address `[Serializable]` until we figure that out.

**Comment by mj1856** [comment]
@tarekgh - Any advice here?  CoreFx stuff is PCL, but the existing `DateTime` struct is in CoreClr, which isn't PCL.  If our work here will go OOB, wouldn't it all need to be PCL, and then how would we support `[Serializable]`, `[IConvertable]`, etc. ?

Also, we had to make our unit tests non-PCL in order to be able to *set* the current culture during the test.  Is there a workaround for that?

Thanks.

**Comment by tarekgh** [comment]
Hi @mj1856, for serialization we can use data contract instead. this should good for this library. eventually if we need to bring this library to the core we'll may need to change that again as we cannot depend on data contract in the core.
For IConvertable, it is added to the new PCL support but talking to some people, it is not really recommended anymore. so you can just not support it and we can support the type conversion in different ways (implicit/explicit cast operators, exposing specific APIs for interesting types FromType/ToType. 

for the test, I am not sure if we have PCL specific test. but anyway whatever test you have should be good enough I think. in the latest version of the System.Globalization contract we have exposed CultureInfo.CurrenCulture setter property. so if you are using the latest version you may use this property to set the culture.

Thanks

**Comment by mj1856** [comment]
@tarekgh  - Thanks!
