### ISSUE TITLE
Range checks (`Between`) should be upper-bound exclusive

### ISSUE THREAD

**Issue by Clockwork-Muse** [mj1856/corefx-dateandtime#22]
Range checks, like for all positive contiguous-range types, should use an exclusive upper-bound (that is, `<`).

There's [this blog post](http://www2.sqlblog.com/blogs/aaron_bertrand/archive/2011/10/19/what-do-between-and-the-devil-have-in-common.aspx) talking about some of the problems encountered in SQL Server with an inclusive bound, but it's actually far larger than that:  
The problem is inherent in how numbers are represented.  If you're working with any non-integral-count type, there's always a smaller slice between two values.  Using an inclusive bound requires people to ask about the full range of precision, even when all they care about is a coarser-grained slice.

Say I'm asking about the complete hour `1700` ("If dinner starts between 1700 and 1800, I am happy").  since the bound is inclusive, the end is annoying: 

    If (dinnerStart.IsBetween(new TimeOfDay(17, 0), new TimeOfDay(17, 59, 59, 99999999))) 

...I have to specify the complete precision.  If it's exclusive:

    If (dinnerStart.IsBetween(new TimeOfDay(17, 0), new TimeOfDay(18, 0))) 

...I'll have an easier time finishing so my dinner starts on time (and I'll be happy).

It's also far easier to spot errors with an exclusive bound.  How many `9`s did I specify as part of fractional seconds?  Why might that be a problem?  What happens to my check when/if `TimeOfDay` supports better precision?

**Comment by mj1856** [comment]
Completely agree, and I believe they're *already* using an exclusive upper bound.  Are you seeing something otherwise?

**Comment by Clockwork-Muse** [comment]
Sorry, you're right.  Somehow I though I saw `>=` in `TimeOfDay.IsBetween(...)`.  Maybe because the conditions were opposite what I was expecting?

**Comment by mj1856** [comment]
Here's the implementation (annotated)

```
return startTicks <= endTicks    // detects whether the range spans midnight or not
    ? (startTicks <= _ticks && endTicks > _ticks) // range test when the range doesn't span midnight
    : (startTicks <= _ticks || endTicks > _ticks);  // range test when the range DOES span midnight
```
