### ISSUE TITLE
Move to corefxlab?

### ISSUE THREAD

**Issue by rafidka** [mj1856/corefx-dateandtime#23]
Isn't corefxlab the right place for the dateandtime package?

https://github.com/dotnet/corefxlab

**Comment by mj1856** [comment]
Perhaps.  I asked @KrzysztofCwalina [on Gitter](https://gitter.im/dotnet/corefx?at=54f8d2f0e172474214a861fc) and the response was:

> I would say corefxlab if it's a speculative proposal and can be out-of-band. If it's more solid or requires changes to existing APIs (as opposed to extensions) then Corefx might be the best approach. Also, you could chose not too worry about the repo for now. Create a proposal and submit it as an issue. We can then take it through the normal API design process we have for CoreFx. During the process we can decide which repo is best

Let's keep working here for now.  When we're ready, I'll open a new issue on corefx and they can decide if it should go in corefx or corefxlab.

**Comment by rafidka** [comment]
Thanks @mj1856. Closing.
