### ISSUE TITLE
Support Serialization

### ISSUE THREAD

**Issue by mj1856** [mj1856/corefx-dateandtime#27]
Per Tarek's comment [here](https://github.com/mj1856/corefx-dateandtime/issues/2#issuecomment-89106354) we should implement `DataContract` on the new types.

**Comment by mj1856** [comment]
Added in 27166e.

**Comment by tarekgh** [comment]
For now it is ok to implement IXmlSerializable. but if we need to have this in the future in coreclr, it'll depend on which contract will belong to. if we need it in System.Runtime then this will not work (even will not work with DataContract as System.Runtime cannot depend on System.Xml.XmlSerializer. but if we put it in another layer that will be ok. anyway we can figure this out when we need to.
Thanks.

**Comment by mj1856** [comment]
@tarekgh  - Ok.  I'll leave it as-is for now.  The current plan is to complete this as a PCL, then your team can decide whether to keep it OOB or merge it in, making adjustments as necessary.  Thanks!

**Comment by tarekgh** [comment]
we need to let the people start using your OOB so we can have idea if we need to bring this functionality to the core. as we said before we need to have it proven in the field and then bring it to the core. 
thanks again for your dedication to get this done. I this this will help the community.
