### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rafidka** [mj1856/corefx-dateandtime#4]
Thanks @mj1856 for your efforts. I just noticed that there is not enough documentation in your code. Here are some examples:

1. Constructors and methods don't have XML documentation.
2. It is not easy to tell what the meaning of day number is in MinDayNumber and MaxDayNumber. My first impression was the number of days since 0 A.D. But then why would the date be restricted to 0 A.D? What about history applications?

**Comment by rafidka** [comment]
Are you open to help or you prefer to do this yourself? In general (not just about this topic), you mentioned few things in your comment (https://github.com/dotnet/corefx/issues/700#issuecomment-77997867), can we help with those things (optimization, unit tests, documentation, etc.)?

**Comment by mj1856** [comment]
Yes.  I completly agree.  I just wanted to get what I had done out there so we could start discussing.

Please feel free to send PR with any changes you like.  Please do a separate PR for different types of things so the discussions can stay distinct.

**Comment by mj1856** [comment]
Regarding the chosen epoch - I think its important to use the same 0001-01-01 date that `DateTime` and `DateTimeOffset` use.  SQL `datetime2` is the same as well.

**Comment by rafidka** [comment]
Sure, I will send PR once I am one with my changes.

Yeah, I agree that the same epoch should be used. But then I am wondering why MinDayNumber is 0? How can we then represent dates B.C?

**Comment by mj1856** [comment]
IMHO, we shouldn't try to support BCE dates.  We need to align with the range and precision of existing types.

Consider if we *did* support BCE:

```csharp
Date date = new Date(-999, 1, 1);
TimeOfDay time = new TimeOfDay(0,0,0);
DateTime dateTime = date.At(time);  // ArgumentOutOfRangeException!
```

Alignment is important.   I'd argue that if one needs to work with BCE dates, that is another case where they should use [Noda Time](http://nodatime.org), which has a distinct concept of "eras" that can apply across the spectrum of types.

**Comment by paulirwin** [comment]
I agree with @mj1856. SQL Server, ANSI SQL, HTML5, and System.DateTime all use year 1 CE forward. The ISO8601 standard and xsd:date specification looks like it does support negative years for BCE, but considering the other incompatibilities I would say it's not worth the added complexity.

**Comment by mj1856** [comment]
Migrated BCE Date discussion to #8.  Let's track the status of documentation (xml summary comments, etc.) in this issue thread.

**Comment by rafidka** [comment]
I am happy to work on this if you want.

**Comment by mj1856** [comment]
Feel free to work on expanding the xml comments as you see fit. Send a PR when ready for review.  We can do it a little at a time, or all at once.  Whichever you prefer.  And thanks!

**Comment by rafidka** [comment]
I added documentation to only few members in Date structure now to get some feedback before I spend time documenting the rest. One question I have is what should the scope of documentation be? Should I aim at adding full documentation including tags like <summary>, <remarks>, <example>, or for now you think it is enough to live with simple documentation? Interestingly, it seems that not much of .NET Core is documented (well I didn't check all the source code, but I am judging from the fact that even System.Console is not documented)! What is the documentation plan for .NET Core? I didn't see anything about it in the Developer's Guide.

**Comment by mj1856** [comment]
I think you did a good amount in the PR.  I made some notes for you to address.

We want to do enough in this stage to make the API crystal clear, but we don't need to do too much more than that.  Whatever is done here will likely be rehashed if/when it gets merged into corefx.  We have no guarantees right now, we're just working together to solidify a proposal. :)

**Comment by mj1856** [comment]
I've started fleshing out the remaining documentation.  Will be adding more over the next week or so.  Feel free to jump in if you like.

WRT my Mar 11 comment above, I think we are stable enough now for summary, params, exceptions, return, and *some* remarks for important tidbits.

**Comment by mj1856** [comment]
All public methods (and most private ones) are now documented.
